---
name: "Release"

on:
  push:
    branches:
      - master

jobs:
  release_zip_file:
    name: "Prepare release asset"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v1

      - run: |
          echo "package=antizapret" >> $GITHUB_ENV
          echo "release_version=`git describe --abbrev=0 | sed s/v//`" >> $GITHUB_ENV

      - name: "Setup Git"
        run: |
          git config --global user.name "release"
          git config --global user.email "release@GitHub"

      - name: "Zip component dir"
        run: |
          zip ${{ env.package }}.zip -r ./ -x "bin/*" -x ".github/*"
      - name: "Upload zip to release"
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.package }}.zip
          asset_name: ${{ env.package }}.zip
          tag: ${{ env.release_version }}
          overwrite: true

  releasenotes:
    name: "Prepare releasenotes"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v1

      - name: "Set up Python 3.7"
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: "Install requirements"
        run: |
          python3 -m pip install setuptools wheel
          python3 -m pip install -r ./requirements-dev.txt
      - name: "Update release notes"
        run: python3 ./bin/gen_releasenotes --token ${{ secrets.GITHUB_TOKEN }} --repo ${{ github.repository }} --release `git describe --abbrev=0`
